# Use an official lightweight Python 3.9 base image

FROM python:3.9-slim

# Set the working directory inside the container, all application files will be copied here

WORKDIR /app

# Install system dependencies required for mysqlclient / gcc, libmysqlclient-dev, and pkg-config are essential

RUN apt-get update && apt-get install -y gcc default-libmysqlclient-dev pkg-config && rm -rf /var/lib/apt/lists/*

# Copy dependencies file first to leverage Docker layer caching, This ensures image rebuilds are faster if only code changes

COPY requirements.txt .

# Install Python dependencies inside the container

RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project code into the container

COPY . .

# Expose port 5000 to allow external access to the Flask app

EXPOSE 5000

# Define the default command to run the Flask application

CMD ["python", "app.py"]